### ISSUE TITLE
counting my posts when it shouldn't

### ISSUE THREAD

**Issue by Angular-Angel** [dstorrs/sv_counterbot#1]
I don't know why, but for some reason the bot seems to be counting my posts despite both me using the GM tag and me using the ID tag to start after I had already posted. Is the readme no longer accurate?

**Comment by dstorrs** [comment]
You're using the most recent version, right?  Do a git pull just to be
sure, then try it again.  If that fails, send me the command line that
you're using.

**Comment by Angular-Angel** [comment]
I'm using 1.4. The command I've been using is "./perl_tallyho.pl --page https://forums.sufficientvelocity.com/threads/slivers-adrift-in-infinity.33882/page-7  [--id 162] [--gm Angle]"

**Comment by dstorrs** [comment]
Remove the square brackets.  When I do that it does not include your name.

In the README file, the square brackets refer to optional parameters; I'll
clarify that.

**Comment by dstorrs** [comment]
I've done a fresh push with updated docs and a couple of minor tweaks that
won't matter to you but you should probably have anyway.  Do another pull.

**Comment by Angular-Angel** [comment]
*Facepalm* Right, of course. Thank you! Sorry for being so brainless. XD

**Comment by dstorrs** [comment]
On Mon, Nov 28, 2016 at 3:42 PM, Angular-Angel <notifications@github.com>
wrote:

> *Facepalm* Right, of course. Thank you! Sorry for being so brainless. XD
>

The number of times I've made worse mistakes than that....  :>
